name: demo_test
description: "An Online Bus Ticket Booking System."

publish_to: 'none' # Prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets section to include any assets in the project
  assets:
    - assets/images/
    # Logo of the app
    # - assets/top_photo.jpg     # Top photo in the dashboard
    # - assets/bottom_photo.jpg  # Bottom photo in the dashboard
    # Add other images or files here as needed
